# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("follow", "followed you"),
                    ("like_post", "liked your post"),
                    ("comment", "commented on your post"),
                    ("reply", "replied to your comment"),
                    ("like_comment", "liked your comment"),
                    ("mention", "mentioned you"),
                    ("repost", "reposted your post"),
                    ("quote", "quoted your post"),
                ],
                max_length=20,
            ),
        ),
    ]
